### ISSUE TITLE
Code crashes for low values of N_MAX_PIXEL_SEGMENTS_PER_MODULE

### ISSUE THREAD

**Issue by VourMa** [SegmentLinking/TrackLooper#117]
It was observed that setting the `N_MAX_PIXEL_SEGMENTS_PER_MODULE` variable to low values (500, 5000 and 6000 were tested) causes the code to crash on different events, depending on the value set.

Sample error (using `cuda-memcheck`) for the 1st event with the variable set to 500:
```
========= Invalid __global__ read of size 4
=========     at 0x00000770 in /mnt/data1/evourlio/TrackLooper/SDL/Kernels.cu:125:createSegmentsInGPU(SDL::modules&, SDL::miniDoublets&, SDL::segments&, SDL::objectRanges&)
=========     by thread (28,5,0) in block (0,0,39)
=========     Address 0x7ff6eebffffc is out of bounds
=========     Device Frame:/mnt/data1/evourlio/TrackLooper/SDL/Kernels.cu:125:createSegmentsInGPU(SDL::modules&, SDL::miniDoublets&, SDL::segments&, SDL::objectRanges&) (createSegmentsInGPU(SDL::modules&, SDL::miniDoublets&, SDL::segments&, SDL::objectRanges&) : 0x770)
=========     Saved host backtrace up to driver entry point at kernel launch time
=========     Host Frame:/lib64/libcuda.so.1 [0x2170ba]
=========     Host Frame:/cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_2_0_pre5/external/slc7_amd64_gcc900/lib/libcudart.so.11.0 [0xf7cb]
=========     Host Frame:/cvmfs/cms.cern.ch/slc7_amd64_gcc900/cms/cmssw/CMSSW_11_2_0_pre5/external/slc7_amd64_gcc900/lib/libcudart.so.11.0 (cudaLaunchKernel_ptsz + 0x1c1) [0x3c311]
=========     Host Frame:/mnt/data1/evourlio/TrackLooper/SDL/sdl.so [0x9f8f2]
=========     Host Frame:/mnt/data1/evourlio/TrackLooper/SDL/sdl.so (_Z104__device_stub__Z19createSegmentsInGPURN3SDL7modulesERNS_12miniDoubletsERNS_8segmentsERNS_12objectRangesEPN3SDL7modulesEPNS_12miniDoubletsEPNS_8segmentsEPNS_12objectRangesE + 0x140) [0x9fee0]
=========     Host Frame:/mnt/data1/evourlio/TrackLooper/SDL/sdl.so (_Z19createSegmentsInGPURN3SDL7modulesERNS_12miniDoubletsERNS_8segmentsERNS_12objectRangesE + 0x67) [0x9ff57]
=========     Host Frame:/mnt/data1/evourlio/TrackLooper/SDL/sdl.so (_ZN3SDL5Event27createSegmentsWithModuleMapEv + 0x395) [0x94749]
=========     Host Frame:sdl (_Z10runSegmentPN3SDL5EventE + 0x90) [0x8bea0]
=========     Host Frame:sdl [0x46c01]
=========     Host Frame:/cvmfs/cms.cern.ch/slc7_amd64_gcc900/external/gcc/9.3.0/lib64/libgomp.so.1 (GOMP_parallel + 0x42) [0x11a22]
=========     Host Frame:sdl (_Z7run_sdlv + 0x8ad) [0x495ad]
=========     Host Frame:sdl (main + 0x280f) [0x43b6f]
=========     Host Frame:/lib64/libc.so.6 (__libc_start_main + 0xf5) [0x22555]
=========     Host Frame:sdl [0x45727]
```

**Comment by YonsiG** [comment]
Hi Manos,

   Yes, this was a problem I also meet with. It’s because the N_MAX_PIXEL_SEGMENTS_PER_MODULE is hard coded as 600 in several files. I changed them manually to make it work. I haven’t pushed it to GitHub yet. But you can try changing the “PixelTriplet.cu” and “PixelQuintuplet.cu”,  “Triplet.cu”, “Quintuplet.cu”.

    If everyone agrees on my result in tomorrow meeting, I can push this to GitHub and then you can use it.

Best,
Yanxi

**Comment by VourMa** [comment]
Indeed, hardcoding the number you mention causes problems. However, this corresponds to the value of the `N_MAX_SEGMENTS_PER_MODULE` variable (see [here](https://github.com/SegmentLinking/TrackLooper/blob/953bcdbff0b6003002e56562768865a425de0860/SDL/Kernels.cuh#L40)). I have opened a separate issue about it (see 2nd paragraph of issue #120).
Thank you for taking care of this.

On the other hand, the issue that I mention here is about the pixel version of this variable, `N_MAX_PIXEL_SEGMENTS_PER_MODULE`, which causes problems even if it is changed consistently in all files (as far as I tested, at least).

**Comment by VourMa** [comment]
I guess this is not longer applicable, since we dynamically assign sizes, so it can be closed? @YonsiG @bsathian Maybe you know better?

**Comment by YonsiG** [comment]
Thanks Manos, I think this issue is solved when allocating the GPU kernels, because in kernels, we no longer use fixed memory values. However, in the write_output_ntuples.cc and some corresponding CPU files, there is still remains sitting there. I'll spend some time and take a look at those, then we can remove the N_MAX_xxx completely, and then we can close the issue.
