### ISSUE TITLE
Collect maximum values for objects in one file?

### ISSUE THREAD

**Issue by VourMa** [SegmentLinking/TrackLooper#120]
For the most part, the maximum allowed number of an object is defined in [`Kernel.cuh`](https://github.com/SegmentLinking/TrackLooper/blob/953bcdbff0b6003002e56562768865a425de0860/SDL/Kernels.cuh#L40). However, these numbers are also defined separately in other files, e.g. [`EventForAnalysisInterface.cc`](https://github.com/SegmentLinking/TrackLooper/blob/34df4c1982ff56576bcc0050c3f5811f51834252/code/AnalysisInterface/EventForAnalysisInterface.cc#L5) or [`write_sdl_ntuple.cc`](https://github.com/SegmentLinking/TrackLooper/blob/953bcdbff0b6003002e56562768865a425de0860/code/core/write_sdl_ntuple.cc#L958).

The situation is a bit more complicated when it comes to `N_MAX_SEGMENTS_PER_MODULE`. Except for multiple definitions of the variable, the raw number is also used, e.g. [here](https://github.com/SegmentLinking/TrackLooper/blob/953bcdbff0b6003002e56562768865a425de0860/SDL/PixelTriplet.cu#L329) and [here](https://github.com/SegmentLinking/TrackLooper/blob/953bcdbff0b6003002e56562768865a425de0860/SDL/PixelTriplet.cu#L335).

Would it make sense to put all of these variables in one file, which would then be included in the relevant files, and to replace all the raw numbers with the appropriate variables?

**Comment by tresreid** [comment]
There is a file called constants.h that should be able to have all of these values and pass them to all files (since it isn't a cuda header file). I think that is the place to move all this information.

**Comment by VourMa** [comment]
Fixed in #132
