### ISSUE TITLE
consistent lower pt definition through the code

### ISSUE THREAD

**Issue by slava77** [SegmentLinking/TrackLooper#167]
in a follow up to #166 : 
while this PR is a single character fix, I think that we need some more robust way of keeping track of the pt cut.

- preprocessing time option: use a macro that sets a float ptMin value if `PT0P8` is set and simultaneously sets the prefix in the map files
- compile time option: A constexpr in constants.cuh and perhaps a static assert of some sorts that makes sure that the module maps are made for a matching pt selection (perhaps allowing a tighter pt cut with respect to the lower pt used to get the module mapping is OK).

**Comment by VourMa** [comment]
@bsathian Do I remember correctly that you fixed this some time back? Can it be closed?
