### ISSUE TITLE
Replace `sdl_validate_efficiency` workflow for validation?

### ISSUE THREAD

**Issue by VourMa** [SegmentLinking/TrackLooper#180]
Our current [wiki](https://github.com/SegmentLinking/TrackLooper/wiki/Line-Segment-Tracking-Algorithm#validation-package) proposes the [`sdl_validate_efficiency`](https://github.com/SegmentLinking/TrackLooper/blob/master/efficiency/bin/sdl_validate_efficiency) as our latest script for validation purposes. However, this scripts calls [`sdl_compare_efficiencies`](https://github.com/SegmentLinking/TrackLooper/blob/master/efficiency/bin/sdl_compare_efficiencies), which, in turn, makes a plot comparison with [`plot_compare`](https://github.com/SegmentLinking/TrackLooper/blob/master/efficiency/python/plot_compare.py) against some cpu results pointed by the value of, e.g., `$LATEST_CPU_BENCHMARK_EFF_MUONGUN`, which leads to `/data2/segmentlinking/muonGun_cpu_efficiencies.root`. Since the cpu version of the code is no longer maintained, it seems like this is a pointless comparison and can even lead to confusion.

My proposal would be to replace the currently documented validation workflow with the following procedure:
1. Creation of efficiency plots at the latest master branch (say with git hash `1234567`) with the commands `sdl -i SAMPLE -l -o outputMaster.root; sdl_plot_efficiency -i outputMaster.root -g G -p P -f`, where `G ` corresponds to the pdgId of the particle involve in the sample used (0 for PU200, 13 for muon guns, 211 for pion guns) and `P` defines the pT range (more info in the help of the script but, in general, 4 for low pT (=muonGun) and 0 for high pT (=everything except muonGun).
2. Creation of efficiency plots at the development branch (say with git hash `abcdefg`) with the commands `sdl -i SAMPLE -l -o outputDev.root; sdl_plot_efficiency -i outputDev.root -g G -p P -f`
3. Creation of comparison plots with `sdl_plot_multiple_efficiencies -i SAMPLE -t abcdefg -T 1234567 -m MODE -M MODE -l dev -L master`, where `MODE` depends on the memory option during compilation but is usually `explicit_cache` for our tests.

In case the master or the dev branch contain ucommitted changes, the string `DIRTY` may need to be added after the git hash of each run but this should be evident from the code output/output folder.

**Comment by sgnoohc** [comment]
when PR212 is merged this should be closed.
