### ISSUE TITLE
`sdl_plot_efficiency` Issues without "-l" Flag

### ISSUE THREAD

**Issue by GNiendorf** [SegmentLinking/TrackLooper#189]
No plots get output from sdl_plot_efficiency if you don't include the "-l" flag (for lower-level objects) when you run sdl. The plots that don't require lower-level objects should still be made when the "-l" flag is not included, and the -l flag increases runtime substantially, so this should be fixed eventually.

**Comment by sgnoohc** [comment]
when PR212 is merged this should be closed
