### ISSUE TITLE
Lower efficiency in CMSSW 12 geometry (T24) vs. CMSSW 10 geometry (T6)

### ISSUE THREAD

**Issue by VourMa** [SegmentLinking/TrackLooper#191]
Detailed comparisons and some first thoughts in:
https://indico.cern.ch/event/1186900/contributions/4987459/attachments/2501952/4298042/MigrationToCMSSW12Geometry_ComparisonsAndIssues.pdf

Needs to be addressed before merging PR #190.

As a first check, the pixel maps will be checked.

**Comment by VourMa** [comment]
Adding the updates from yesterday's meeting to this.

After some extra commits in the [LSTGeometry repo](https://github.com/SegmentLinking/LSTGeometry) by Philip and some fixes by me to make the scripts run, the pixel maps for CMSSW 12 geometry were reproduced (all steps until the production of the pixel maps). A few differences of at most 1 module per pixel map bin were observed. The reproduced pixel maps were used to check any performance changes: [reproduced pixel maps](https://www.classe.cornell.edu/~evourlio/www/SDL_GPU/checkPixelMaps/eff_plots__GPU_explicit_cache_f87e39bDIRTY_PU200_n100_reproducedPixelMaps/) vs. [nominal pixel maps](https://uaf-10.t2.ucsd.edu/~evourlio/SDL/moveToCMSSW12Geometry/eff_plots__GPU_explicit_cache_f87e39b_PU200_n100_beforeChanges/). The differences were minimal, so I don't think that the pixel maps are the source of the lower CMSSW 12 geometry.

**Question/proposal:** Should I commit the reproduced pixel maps to the `TrackLooper/data` directory of our repo, so that we have all of the map information uploaded? I think they are the only input information not pushed online yet.

Also, the comparison of CMSSW 10 vs. CMSSW 12 geometries with |η| < 2.4 and with extra stats:
- [500 PU200 events](https://uaf-10.t2.ucsd.edu/~evourlio/SDL/moveToCMSSW12Geometry/eff_comparison_plots__f87e39bDIRTY_explicit_cache_n500_beforeChanges_EtaRestr_ExtraStats_f87e39bDIRTY_explicit_cache_n500_CMSSW10Ref_EtaRestr_ExtraStats_PU200/) -> ~2% lower efficiency and ~2% higher fake rate for CMSSW 12
- [1000 muonGun events](https://uaf-10.t2.ucsd.edu/~evourlio/SDL/moveToCMSSW12Geometry/eff_comparison_plots__f87e39b_explicit_cache_n1000_beforeChanges_EtaRestr_ExtraStats_f87e39bDIRTY_explicit_cache_n1000_CMSSW10Ref_EtaRestr_ExtraStats_muonGun/) -> Comparable efficiency, except maybe for the turn-on, where CMSSW 12 is consistently a couple of % lower
- [1000 muonGun_highE events](https://uaf-10.t2.ucsd.edu/~evourlio/SDL/moveToCMSSW12Geometry/eff_comparison_plots__f87e39b_explicit_cache_n1000_beforeChanges_EtaRestr_ExtraStats_f87e39bDIRTY_explicit_cache_n1000_CMSSW10Ref_EtaRestr_ExtraStats_muonGun_highE/) -> Comparable performance overall.

**Comment by slava77** [comment]
![image](https://user-images.githubusercontent.com/4676718/190452794-3b7bf9d7-8726-421a-ac50-814ae4f5a618.png)

a comparison of the built track efficiency for the initial step
- black is 12_5_0_pre5 (has a problem compared to 1250pre4; unrelated to this issue, but something to keep in mind if we are looking for a more recent release)
- The orange is I think our old 104X: it has a much larger efficiency. This is to confirm that quadruplet pLS is expected to be lower in 12X based on this 

(previously shared on skype).

We could consider closing the issue, since the problem seems to be external, in the pLS.
