### ISSUE TITLE
Is the pixelSegmentIndex -> and the pt/eta/phi being correctly read for pT3 and pT5?

### ISSUE THREAD

**Issue by sgnoohc** [SegmentLinking/TrackLooper#207]
the pt values for the pLS from pT3 and pT5 are read here:
https://github.com/SegmentLinking/TrackLooper/blob/master/code/core/write_sdl_ntuple.cc#L1229
the indexing is done like

innerTrackletInnerSegmentIndex - rangesInGPU.segmentModuleIndices[*(modulesInGPU.nLowerModules)]

However, for pT5 it's like this:
https://github.com/SegmentLinking/TrackLooper/blob/master/code/core/write_sdl_ntuple.cc#L1117

While, for pT3 it's like this:
https://github.com/SegmentLinking/TrackLooper/blob/master/code/core/write_sdl_ntuple.cc#L1089

They don't seem consistent

Are they correct?

It seems like one is wrong and one is right.

**Comment by sgnoohc** [comment]
https://github.com/SegmentLinking/TrackLooper/blob/master/SDL/TrackCandidate.cu#L185
I see it's because this one passes pixelIndices, while for pT3,
https://github.com/SegmentLinking/TrackLooper/blob/master/SDL/TrackCandidate.cu#L343
It passes the pT3 index.

This needs to be cleaned up....

**Comment by VourMa** [comment]
@sgnoohc Was this fixed as a part of the updates you did to the output code? I would say yes and, if you confirm, let's close the issue.
