### ISSUE TITLE
pt estimates for T3s and T5s

### ISSUE THREAD

**Issue by sgnoohc** [SegmentLinking/TrackLooper#215]
We should use "circles" to estimate pts not relying on the weird "delta betas".

cf. https://github.com/SegmentLinking/TrackLooper/issues/214

**Comment by sgnoohc** [comment]
N.B. we should do this after PR212 is merged.

**Comment by YonsiG** [comment]
This issue has been solved in writing output ntuples in #388 
Betas are removed from pt calculations
