### ISSUE TITLE
Issues with Pixel Segment Code

### ISSUE THREAD

**Issue by GNiendorf** [SegmentLinking/TrackLooper#223]
1. Variables are not directly copied to the correct location. They are first allocated with temporary device variables, and then manually copied in the kernel (addPixelSegmentToMemory device function).
https://github.com/SegmentLinking/TrackLooper/blob/cff3eda1228855233f5be55620aee06c0d3464b5/SDL/Event.cu#L830-L846

2. SegmentsInGPU is allocated with a large constant amount of space, instead of using the correct "size" variable.
https://github.com/SegmentLinking/TrackLooper/blob/cff3eda1228855233f5be55620aee06c0d3464b5/SDL/Event.cu#L765-L768

3. createMDArrayRanges and createSegmentArrayRanges both make the mistake of pulling variables from the GPU, computing some quantities on the CPU, and then pushing the results back to the GPU instead of just calculating everything directly on the GPU.
https://github.com/SegmentLinking/TrackLooper/blob/4015cfcb67b215aee3eaf990e4ab4d3135392c1f/SDL/Segment.cu#L32-L103

**Comment by GNiendorf** [comment]
Issue 3 is now fixed by #272, thank you @tresreid!

**Comment by VourMa** [comment]
...And I believe that issue 2 is a necessary evil, as showcased in PR #342. Should we close this? @GNiendorf
