### ISSUE TITLE
LSTPerformanceWeb needs update to incorporate r_vertex plot

### ISSUE THREAD

**Issue by sgnoohc** [SegmentLinking/TrackLooper#277]
this PR added r_vertex plot: https://github.com/SegmentLinking/TrackLooper/pull/276
However the html has not been updated yet.
Some ... scripting needs to be done to add those in and deploy the copies of LSTPerformanceWeb on phi3/lnx7188/hpg.

**Comment by ariostas** [comment]
Closed by https://github.com/SegmentLinking/LSTPerformanceWeb/pull/2
