### ISSUE TITLE
More CudaFree's Than CudaMalloc's on Master

### ISSUE THREAD

**Issue by GNiendorf** [SegmentLinking/TrackLooper#285]
On the master branch I noticed that there are more calls to cudaFree than cudaMalloc:

Running over all events (the 1000 gets changed to max events ~175): `nvprof ./bin/sdl -n 1000 -v 1 -w 0 -s 8 -i PU200`

I get the following:

`15.38%  5.09434s  1344  3.7904ms  1.6920us  4.65437s  cudaMalloc`
`0.17%  55.389ms   1358  40.786us     513ns  353.44us  cudaFree`

Meaning that there were 1344 calls to cudaMalloc and 1358 to cudaFree. The host caching allocator seems to be fine though:

`0.10%  32.912ms       113  291.26us  3.5400us  5.2594ms  cudaHostAlloc`
`0.02%  6.6083ms       113  58.480us  3.9990us  2.1022ms  cudaFreeHost`

**Comment by GNiendorf** [comment]
It seems like the difference is independent of the number of events being run. For one event:

`47.44%  317.77ms       193  1.6465ms  1.5070us  310.20ms  cudaMalloc`
`0.93%  6.2324ms       207  30.108us     489ns  195.84us  cudaFree`

**Comment by VourMa** [comment]
The problem is with multi-streaming.

```nvprof sdl -i PU200 -n 1 -s 1 -w 0```
![image](https://github.com/SegmentLinking/TrackLooper/assets/15358704/e8c3a9ba-7dcd-4fed-9c38-0b76259f8f5a)

```nvprof sdl -i PU200 -n 1 -s 8 -w 0```
![image](https://github.com/SegmentLinking/TrackLooper/assets/15358704/91d07b7d-58e9-4fd5-b46e-8745dca6b02f)

**Comment by GNiendorf** [comment]
Just to log this, I saw that there were two cudaFree's being called right before each stream was destroyed
![here](https://github.com/SegmentLinking/TrackLooper/assets/25272611/e431565c-2f2d-4576-8544-ba4ea1ff295f)
Tres pointed out that it's probably coming from
https://github.com/SegmentLinking/TrackLooper/blob/4d0158d7afbf293bab50e7611c42067100e249a1/SDL/Event.cu#L259
Which is called for each stream that's destroyed, but these maps are only created once (before the streams are even created)
https://github.com/SegmentLinking/TrackLooper/blob/4d0158d7afbf293bab50e7611c42067100e249a1/SDL/EndcapGeometry.cu#L65-L69
This function was introduced in my old hit loading speedup PR here #181
