### ISSUE TITLE
Considerations on memory management

### ISSUE THREAD

**Issue by VourMa** [SegmentLinking/TrackLooper#287]
While investigating issue #285, I came across a couple of points in our code where the memory allocations seemed a bit weird/bug-prone. Let me mention them below, so that more people can take a look and let me know if I am missing something:

- [x] 1. The allocation of the `indicesOfEligibleT5Modules` happens in `Event.cu` https://github.com/SegmentLinking/TrackLooper/blob/4d0158d7afbf293bab50e7611c42067100e249a1/SDL/Event.cu#L1257-L1261 instead of in `Module.cu` https://github.com/SegmentLinking/TrackLooper/blob/4d0158d7afbf293bab50e7611c42067100e249a1/SDL/Module.cu#L12 where the relevant memory is then freed https://github.com/SegmentLinking/TrackLooper/blob/4d0158d7afbf293bab50e7611c42067100e249a1/SDL/Module.cu#L108 I see no reason for this, and I would propose to move the memory allocation to `Module.cu`.

- [x] 2. We have only one way to allocate the modulesInGPU https://github.com/SegmentLinking/TrackLooper/blob/4d0158d7afbf293bab50e7611c42067100e249a1/SDL/Module.cu#L76-L106 but two ways to free the memory
https://github.com/SegmentLinking/TrackLooper/blob/4d0158d7afbf293bab50e7611c42067100e249a1/SDL/Module.cu#L166-L203 and https://github.com/SegmentLinking/TrackLooper/blob/4d0158d7afbf293bab50e7611c42067100e249a1/SDL/Module.cu#L204-L244 Any reason for this that I am missing? Otherwise, I think we should just remove the extra memory-freeing functions.

- [ ] 3. Finally, I would like to ask why these variables https://github.com/SegmentLinking/TrackLooper/blob/4d0158d7afbf293bab50e7611c42067100e249a1/SDL/Event.cu#L4-L7 are defined in the global scope. I would expect them to be inside the `Event` class or defined in the appropriate file where they are relevant.

**Comment by GNiendorf** [comment]
#292 Deals with issue two by deleting the cached version since we've agreed previously to not use the caching allocator here. Both will actually be deleted when that area of the code moves to Alpaka since the buffers are freed automatically.

**Comment by VourMa** [comment]
More instances of variables in global scope (sub-issue 3 above):

https://github.com/SegmentLinking/TrackLooper/blob/6e6e2d0612a9c67223b72da25fb5bf5ff4b6c848/SDL/Module.cu#L5-L9

https://github.com/SegmentLinking/TrackLooper/blob/6e6e2d0612a9c67223b72da25fb5bf5ff4b6c848/SDL/ModuleConnectionMap.cc#L3-L24

**Comment by GNiendorf** [comment]
One more instance of variables in global scope:

https://github.com/SegmentLinking/TrackLooper/blob/c58c36e401d4d52b9f859c996a0840223bb15aea/SDL/TiltedGeometry.cc#L3

**Comment by VourMa** [comment]
@GNiendorf subissue 3 is still open but was subissue 1 dealt with during the Alpaka migration?

**Comment by GNiendorf** [comment]
@VourMa Yup, subissue 1 is fixed!

**Comment by VourMa** [comment]
Given that we found a work-around for thread-safety of global variables, should we close this issue?

**Comment by VourMa** [comment]
@slava77 @GNiendorf Is subissue 3 of this issue closed by the #377?

**Comment by slava77** [comment]
> @slava77 @GNiendorf Is subissue 3 of this issue closed by the #377?

do you mean 
```
uint16_t SDL::nModules; 
 uint16_t SDL::nLowerModules; 
```
?

Well, they are still in a "global" space in `SDL::Gloabals`.
I'm not sure though what the text in subissue 3 implied.

**Comment by GNiendorf** [comment]
I think this can be closed now, right @VourMa?

**Comment by VourMa** [comment]
I would say so, yes. Closing and we can reopen a new, more dedicated one if we see anymore problems.
