### ISSUE TITLE
Fix code style

### ISSUE THREAD

**Issue by VourMa** [SegmentLinking/TrackLooper#290]
The indentation, and the style in general, is all over the place, all over the code. This creates issues understanding the code and even developing it every now and then. 

It would be useful to run the whole code through clang-format at some point and implement a CI to keep newly changed files tidy. A code snippet to do that was provided by @pwittich [here](https://github.com/apollo-lhc/cm_mcu/blob/cd555aaac104af2ab433197d4a3231bb58e39ade/.github/workflows/c-cpp.yml#L100-L126).
The CI can be set up independently and already start working on the files that we change from now on.

**Comment by GNiendorf** [comment]
@VourMa Is this still an issue? Figure we should close this.

**Comment by VourMa** [comment]
Indeed, this can be closed given all the work on the CI by Andres. Closing now.
