### ISSUE TITLE
Incorrect and Ambiguous Uses of Cuda Memset

### ISSUE THREAD

**Issue by GNiendorf** [SegmentLinking/TrackLooper#293]
Incorrect Uses (Value is set to some unknown junk instead of intended value)

https://github.com/SegmentLinking/TrackLooper/blob/b498de813de1855c719367894c6f79acfa831d18/SDL/Event.cu#L897

https://github.com/SegmentLinking/TrackLooper/blob/b498de813de1855c719367894c6f79acfa831d18/SDL/Event.cu#L681

https://github.com/SegmentLinking/TrackLooper/blob/b498de813de1855c719367894c6f79acfa831d18/SDL/Segment.cu#L168

Ambiguous use cases where each byte is set to -1, which corresponds to 255 in decimal representation.

https://github.com/SegmentLinking/TrackLooper/blob/b498de813de1855c719367894c6f79acfa831d18/SDL/Hit.cu#L92-L96

https://github.com/SegmentLinking/TrackLooper/blob/b498de813de1855c719367894c6f79acfa831d18/SDL/Event.cu#L1261

https://github.com/SegmentLinking/TrackLooper/blob/b498de813de1855c719367894c6f79acfa831d18/SDL/Module.cu#L978-L988

Unnecessary Memset Case (set by memcpy after it is initialized in Event.cu)

https://github.com/SegmentLinking/TrackLooper/blob/b498de813de1855c719367894c6f79acfa831d18/SDL/Hit.cu#L91

**Comment by VourMa** [comment]
@GNiendorf Should we close this?

**Comment by GNiendorf** [comment]
@VourMa Let's leave it open for right now, because this relates to some of the compiler warnings that we see. Specifically the memsets to -1.

**Comment by VourMa** [comment]
@GNiendorf To be closed now, since the Alpaka version has been merged into master? Or are still affected by this in the master?

**Comment by GNiendorf** [comment]
@VourMa Final memset issues should be fixed by PR #383
