### ISSUE TITLE
Remove Remaining Legacy CPU Code After Alpaka Move

### ISSUE THREAD

**Issue by GNiendorf** [SegmentLinking/TrackLooper#306]
[Hit.cc](https://github.com/SegmentLinking/TrackLooper/blob/alpaka_move/code/core/Hit.cc),  [Hit.h](https://github.com/SegmentLinking/TrackLooper/blob/alpaka_move/code/core/Hit.h),  [MathUtil.cc](https://github.com/SegmentLinking/TrackLooper/blob/alpaka_move/code/core/MathUtil.cc), and [MathUtil.h](https://github.com/SegmentLinking/TrackLooper/blob/alpaka_move/code/core/MathUtil.h) should be removed from /code/core and replaced with the relevant Alpaka functions where needed.

**Comment by VourMa** [comment]
What do we miss to be done with this issue? From a quick look, I couldn't find where we are using the files mentioned in the issue description.

**Comment by GNiendorf** [comment]
Yes, the code is still used in the GNN ntuple code: The function setGnnNtupleBranches for example.
