### ISSUE TITLE
Alpaka Kernel Launch Parameter Search, CUDA and CPU backends

### ISSUE THREAD

**Issue by GNiendorf** [SegmentLinking/TrackLooper#307]
Opening this issue as a continuation of #295 to keep a log of kernel launch parameter studies for both the CUDA and CPU backends.

**Comment by GNiendorf** [comment]
Closing this since timing isn't really a concern right now.

**Comment by VourMa** [comment]
I would argue that, for CPU, timing is something to be improved - but I am not sure if there is anything to gain by such an optimization.
