### ISSUE TITLE
Move static variables to static functions

### ISSUE THREAD

**Issue by VourMa** [SegmentLinking/TrackLooper#339]
The presence of static variables in our codes causes issues while `scram build`ing in CMSSW. This is because, after compilation, CMSSW tries to write the configuration files for the various producers, which requires the LST shared libraries to be loaded. At that point, any global/static variables are loaded and, if the corresponding backend for which we are compiling is not there (e.g. cuda backend in a machine with no NVIDIA GPU), `scram` crashes.

Ideally, we should not change our compilation targets based on the machine used but rather choose the backend to run during runtime. The solution for the issue above is to move the static variables to static functions. This way, we can still define global variables in those functions, but the global/static variables will only be created when the functions are called and not during loading the library.

**Comment by VourMa** [comment]
@slava77 This is should be closed by your #377, right?

**Comment by slava77** [comment]
> @slava77 This is should be closed by your #377, right?

OK, closed. Although the solution was not using the proposal in this issue.
