### ISSUE TITLE
move CMSSW base to 14_1_X

### ISSUE THREAD

**Issue by slava77** [SegmentLinking/TrackLooper#372]
At the end of 14_0_X cycle the pixel tracking alpaka implementation was merged (in 14_0_0_pre3). Also, alpaka 1.1.0 was integrated.
A combination of these is a good motivation to update our reference from 13_3 to 14_1.

CMSSW_14_1_0_pre0 could be a good start, although if we get to it by next week, a pre1 may be available already.

**Comment by slava77** [comment]
@ariostas 
are you available to have a look? (since you made the update the last time).

**Comment by ariostas** [comment]
Yeah, I'll take a look
