### ISSUE TITLE
The previous step2 file is incompatible with CMSSW_14_1_X

### ISSUE THREAD

**Issue by ariostas** [SegmentLinking/TrackLooper#378]
The CI was running into segfaults with CMSSW_14_1_0_pre0 after I switched to using the full file with 100 events, but it worked briefly while it was still using a newer file that only had 10 events.

I was able to reproduce the issue on the UCSD and Cornell machines, and after some testing I verified that the issue was the old step2 file.

I'm generating a new step2 file with 100 events using CMSSW_14_1_0_pre0 and we'll have to deploy it to the CI, and the UCSD and Cornell machines.

**Comment by slava77** [comment]
@ariostas   what's the `cmsDriver` command used for testing?
where is the reference step2 file coming from? 
is it one from `evourlio/LST/samples/RelValTTbarForCMSSW1300pre4/CMSSW_13_0_0_pre4/RelValTTbar_14TeV/GEN-SIM-DIGI-RAW/130X_mcRun4_realistic_v2_2026D88PU200-v1/` ?

**Comment by ariostas** [comment]
@slava77 it's this one: `evourlio/LST/step2_21034.1_100Events.root`

**Comment by slava77** [comment]
> @slava77 it's this one: `evourlio/LST/step2_21034.1_100Events.root`

the provenance shows that this was in CMSSW_13_0_0_pre4. I'm aware of some L1-related data format changes; but then we are not reading L1 objects, not obvious if it's still possibly related.

anyways, it sounds like it's not a part of a large production.
It should be more straightforward to reproduce this file.
I suggest to use `HLT:@fake` in step2; perhaps even try without `L1TrackTrigger,L1`: the output file will be a bit smaller and will also not have products that we are not using.

**Comment by ariostas** [comment]
@slava77 @VourMa Could someone who has write permissions to `/data2/segmentlinking` on cgpu-1 create a `CMSSW_14_1_0_pre0` directory and make a symlink to `/ceph/cms/store/user/anriosta/LST/samples/CMSSW_14_1_0_pre0/step2_21034.1_100Events.root`?

**Comment by VourMa** [comment]
I can do it.

**Comment by VourMa** [comment]
Done!
