### ISSUE TITLE
Small issue when compiling for arm64

### ISSUE THREAD

**Issue by ariostas** [SegmentLinking/TrackLooper#398]
There's a Werror that happens when compiling for arm64. It happens due to this definition.

https://github.com/SegmentLinking/TrackLooper/blob/9f96deeb3ee7b4d99fe2f8175417e50d62f6a8a0/SDL/Kernels.h#L421

Here's the Werror that it shows.

```
Kernels.h:427:30: error: comparison is always false due to limited range of data type [-Werror=type-limits]
  427 |           else if (quad_diff < 0)
      |                    ~~~~~~~~~~^~~
```

We should change it to a `int8_t` since when it's included in CMSSW it will need to be compiled for arm64.

There is also another issue with the rooutil makefile, but we can just ignore that. I'm just trying to run things locally on my laptop since it might be a bit faster to debug. I'll report if I find any other issues with arm64.

**Comment by pwittich** [comment]
According to [this page](https://developer.apple.com/documentation/xcode/writing-arm64-code-for-apple-platforms) at least on apple arm64 platforms `int8_t` and `char` are both single byte signed types?

**Comment by ariostas** [comment]
Thanks @pwittich. I'm using a EL9 Docker image and it seems like for Linux arm64 `char`s are unsigned due to historical reasons (if the comments in [this discussion](https://news.ycombinator.com/item?id=18269886) are true)

**Comment by pwittich** [comment]
What a mess

**Comment by slava77** [comment]
Let's change from `char` used as numerical values to `int8_t`
